// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class AFileHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(AFileHolder.class.getName());

    private String fileLink;
    private String originalName;
    private String manifestUri;

    public void setFileLink(String FileLink) {
        this.fileLink = FileLink;
    }

    public String getFileLink() {
        return this.fileLink;
    }

    public void setOriginalName(String OriginalName) {
        this.originalName = OriginalName;
    }

    public String getOriginalName() {
        return this.originalName;
    }

    public void setManifestUri(String ManifestUri) {
        this.manifestUri = ManifestUri;
    }

    public String getManifestUri() {
        return this.manifestUri;
    }

    public AFileHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("AFile(");
        str.append(" fileLink=").append(getFileLink());
        str.append(" originalName=").append(getOriginalName());
        str.append(" manifestUri=").append(getManifestUri());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getFileLink()));
        str.append(fmt(getOriginalName()));
        str.append(fmt(getManifestUri()));
        return str.toString();
    }

}

