// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class AnsMoneyPayHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(AnsMoneyPayHolder.class.getName());

    private String stan;
    private String timeStamp;
    private String remName;
    private String remID;
    private String notice;
    private String message;
    private String advice;
    private String approvalCode;
    private String cardTxID;
    private FundsHolder dstFunds;
    private FundsHolder payFunds;
    private DstPayRateHolder dstPayRate;
    private ExtFundsHolder[] taxFunds;
    private ExtFundsHolder[] feeFunds;
    private String docID;
    private String docDate;
    private String checkData;
    private BigDecimal state;
    private String signature;

    public void setStan(String Stan) {
        this.stan = Stan;
    }

    public String getStan() {
        return this.stan;
    }

    public void setTimeStamp(String TimeStamp) {
        this.timeStamp = TimeStamp;
    }

    public String getTimeStamp() {
        return this.timeStamp;
    }

    public void setRemName(String RemName) {
        this.remName = RemName;
    }

    public String getRemName() {
        return this.remName;
    }

    public void setRemID(String RemID) {
        this.remID = RemID;
    }

    public String getRemID() {
        return this.remID;
    }

    public void setNotice(String Notice) {
        this.notice = Notice;
    }

    public String getNotice() {
        return this.notice;
    }

    public void setMessage(String Message) {
        this.message = Message;
    }

    public String getMessage() {
        return this.message;
    }

    public void setAdvice(String Advice) {
        this.advice = Advice;
    }

    public String getAdvice() {
        return this.advice;
    }

    public void setApprovalCode(String ApprovalCode) {
        this.approvalCode = ApprovalCode;
    }

    public String getApprovalCode() {
        return this.approvalCode;
    }

    public void setCardTxID(String CardTxID) {
        this.cardTxID = CardTxID;
    }

    public String getCardTxID() {
        return this.cardTxID;
    }

    public void setDstFunds(FundsHolder DstFunds) {
        this.dstFunds = DstFunds;
    }

    public FundsHolder getDstFunds() {
        return this.dstFunds;
    }

    public void setPayFunds(FundsHolder PayFunds) {
        this.payFunds = PayFunds;
    }

    public FundsHolder getPayFunds() {
        return this.payFunds;
    }

    public void setDstPayRate(DstPayRateHolder DstPayRate) {
        this.dstPayRate = DstPayRate;
    }

    public DstPayRateHolder getDstPayRate() {
        return this.dstPayRate;
    }

    public void setTaxFunds(ExtFundsHolder[] TaxFunds) {
        this.taxFunds = TaxFunds;
    }

    public ExtFundsHolder[] getTaxFunds() {
        return this.taxFunds;
    }

    public void setFeeFunds(ExtFundsHolder[] FeeFunds) {
        this.feeFunds = FeeFunds;
    }

    public ExtFundsHolder[] getFeeFunds() {
        return this.feeFunds;
    }

    public void setDocID(String DocID) {
        this.docID = DocID;
    }

    public String getDocID() {
        return this.docID;
    }

    public void setDocDate(String DocDate) {
        this.docDate = DocDate;
    }

    public String getDocDate() {
        return this.docDate;
    }

    public void setCheckData(String CheckData) {
        this.checkData = CheckData;
    }

    public String getCheckData() {
        return this.checkData;
    }

    public void setState(BigDecimal State) {
        this.state = State;
    }

    public BigDecimal getState() {
        return this.state;
    }

    public void setSignature(String Signature) {
        this.signature = Signature;
    }

    public String getSignature() {
        return this.signature;
    }

    public AnsMoneyPayHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("AnsMoneyPay(");
        str.append(" stan=").append(getStan());
        str.append(" timeStamp=").append(getTimeStamp());
        str.append(" remName=").append(getRemName());
        str.append(" remID=").append(getRemID());
        str.append(" notice=").append(getNotice());
        str.append(" message=").append(getMessage());
        str.append(" advice=").append(getAdvice());
        str.append(" approvalCode=").append(getApprovalCode());
        str.append(" cardTxID=").append(getCardTxID());
        str.append(" dstFunds=").append(getDstFunds());
        str.append(" payFunds=").append(getPayFunds());
        str.append(" dstPayRate=").append(getDstPayRate());
        if ( getTaxFunds() != null )
            for (int i=0; i < getTaxFunds().length; i++) {
                str.append(" taxFunds["+i+"]=").append(getTaxFunds()[i]);
            }
        if ( getFeeFunds() != null )
            for (int i=0; i < getFeeFunds().length; i++) {
                str.append(" feeFunds["+i+"]=").append(getFeeFunds()[i]);
            }
        str.append(" docID=").append(getDocID());
        str.append(" docDate=").append(getDocDate());
        str.append(" checkData=").append(getCheckData());
        str.append(" state=").append(getState());
        str.append(" signature=").append(getSignature());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getStan()));
        str.append(fmt(getTimeStamp()));
        str.append(fmt(getRemName()));
        str.append(fmt(getRemID()));
        str.append(fmt(getNotice()));
        str.append(fmt(getMessage()));
        str.append(fmt(getAdvice()));
        str.append(fmt(getApprovalCode()));
        str.append(fmt(getCardTxID()));
        str.append(fmt(getDstFunds()));
        str.append(fmt(getPayFunds()));
        str.append(fmt(getDstPayRate()));
        if ( getTaxFunds() != null )
            for (int i=0; i < getTaxFunds().length; i++) {
                str.append(fmt(getTaxFunds()[i]));
            }
        if ( getFeeFunds() != null )
            for (int i=0; i < getFeeFunds().length; i++) {
                str.append(fmt(getFeeFunds()[i]));
            }
        str.append(fmt(getDocID()));
        str.append(fmt(getDocDate()));
        str.append(fmt(getCheckData()));
        str.append(fmt(getState()));
        return str.toString();
    }

}

