// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class AnsPayCalcHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(AnsPayCalcHolder.class.getName());

    private String stan;
    private String timeStamp;
    private FundsHolder payFunds;
    private DstPayRateHolder dstPayRate;
    private ExtFundsHolder[] taxFunds;
    private ExtFundsHolder[] feeFunds;
    private String signature;

    public void setStan(String Stan) {
        this.stan = Stan;
    }

    public String getStan() {
        return this.stan;
    }

    public void setTimeStamp(String TimeStamp) {
        this.timeStamp = TimeStamp;
    }

    public String getTimeStamp() {
        return this.timeStamp;
    }

    public void setPayFunds(FundsHolder PayFunds) {
        this.payFunds = PayFunds;
    }

    public FundsHolder getPayFunds() {
        return this.payFunds;
    }

    public void setDstPayRate(DstPayRateHolder DstPayRate) {
        this.dstPayRate = DstPayRate;
    }

    public DstPayRateHolder getDstPayRate() {
        return this.dstPayRate;
    }

    public void setTaxFunds(ExtFundsHolder[] TaxFunds) {
        this.taxFunds = TaxFunds;
    }

    public ExtFundsHolder[] getTaxFunds() {
        return this.taxFunds;
    }

    public void setFeeFunds(ExtFundsHolder[] FeeFunds) {
        this.feeFunds = FeeFunds;
    }

    public ExtFundsHolder[] getFeeFunds() {
        return this.feeFunds;
    }

    public void setSignature(String Signature) {
        this.signature = Signature;
    }

    public String getSignature() {
        return this.signature;
    }

    public AnsPayCalcHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("AnsPayCalc(");
        str.append(" stan=").append(getStan());
        str.append(" timeStamp=").append(getTimeStamp());
        str.append(" payFunds=").append(getPayFunds());
        str.append(" dstPayRate=").append(getDstPayRate());
        if ( getTaxFunds() != null )
            for (int i=0; i < getTaxFunds().length; i++) {
                str.append(" taxFunds["+i+"]=").append(getTaxFunds()[i]);
            }
        if ( getFeeFunds() != null )
            for (int i=0; i < getFeeFunds().length; i++) {
                str.append(" feeFunds["+i+"]=").append(getFeeFunds()[i]);
            }
        str.append(" signature=").append(getSignature());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getStan()));
        str.append(fmt(getTimeStamp()));
        str.append(fmt(getPayFunds()));
        str.append(fmt(getDstPayRate()));
        if ( getTaxFunds() != null )
            for (int i=0; i < getTaxFunds().length; i++) {
                str.append(fmt(getTaxFunds()[i]));
            }
        if ( getFeeFunds() != null )
            for (int i=0; i < getFeeFunds().length; i++) {
                str.append(fmt(getFeeFunds()[i]));
            }
        return str.toString();
    }

}

