// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class AnsPayeeAuthHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(AnsPayeeAuthHolder.class.getName());

    private String stan;
    private String timeStamp;
    private String dstCountry;
    private PersonHolder payee;
    private String[] cardCur;
    private String signature;

    public void setStan(String Stan) {
        this.stan = Stan;
    }

    public String getStan() {
        return this.stan;
    }

    public void setTimeStamp(String TimeStamp) {
        this.timeStamp = TimeStamp;
    }

    public String getTimeStamp() {
        return this.timeStamp;
    }

    public void setDstCountry(String DstCountry) {
        this.dstCountry = DstCountry;
    }

    public String getDstCountry() {
        return this.dstCountry;
    }

    public void setPayee(PersonHolder Payee) {
        this.payee = Payee;
    }

    public PersonHolder getPayee() {
        return this.payee;
    }

    public void setCardCur(String[] CardCur) {
        this.cardCur = CardCur;
    }

    public String[] getCardCur() {
        return this.cardCur;
    }

    public void setSignature(String Signature) {
        this.signature = Signature;
    }

    public String getSignature() {
        return this.signature;
    }

    public AnsPayeeAuthHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("AnsPayeeAuth(");
        str.append(" stan=").append(getStan());
        str.append(" timeStamp=").append(getTimeStamp());
        str.append(" dstCountry=").append(getDstCountry());
        str.append(" payee=").append(getPayee());
        if ( getCardCur() != null )
            for (int i=0; i < getCardCur().length; i++) {
                str.append(" cardCur["+i+"]=").append(getCardCur()[i]);
            }
        str.append(" signature=").append(getSignature());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getStan()));
        str.append(fmt(getTimeStamp()));
        str.append(fmt(getDstCountry()));
        str.append(fmt(getPayee()));
        if ( getCardCur() != null )
            for (int i=0; i < getCardCur().length; i++) {
                str.append(fmt(getCardCur()[i]));
            }
        return str.toString();
    }

}

