// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class AttachesHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(AttachesHolder.class.getName());

    private AFileHolder[] aFile;

    public void setAFile(AFileHolder[] AFile) {
        this.aFile = AFile;
    }

    public AFileHolder[] getAFile() {
        return this.aFile;
    }

    public AttachesHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("Attaches(");
        if ( getAFile() != null )
            for (int i=0; i < getAFile().length; i++) {
                str.append(" aFile["+i+"]=").append(getAFile()[i]);
            }
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        if ( getAFile() != null )
            for (int i=0; i < getAFile().length; i++) {
                str.append(fmt(getAFile()[i]));
            }
        return str.toString();
    }

}

