// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class AuthenticationHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(AuthenticationHolder.class.getName());

    private DataAuthenticationHolder[] dataAuthentication;
    private OriginAuthenticationHolder originAuthentication;

    public void setDataAuthentication(DataAuthenticationHolder[] DataAuthentication) {
        this.dataAuthentication = DataAuthentication;
    }

    public DataAuthenticationHolder[] getDataAuthentication() {
        return this.dataAuthentication;
    }

    public void setOriginAuthentication(OriginAuthenticationHolder OriginAuthentication) {
        this.originAuthentication = OriginAuthentication;
    }

    public OriginAuthenticationHolder getOriginAuthentication() {
        return this.originAuthentication;
    }

    public AuthenticationHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("Authentication(");
        if ( getDataAuthentication() != null )
            for (int i=0; i < getDataAuthentication().length; i++) {
                str.append(" dataAuthentication["+i+"]=").append(getDataAuthentication()[i]);
            }
        str.append(" originAuthentication=").append(getOriginAuthentication());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        if ( getDataAuthentication() != null )
            for (int i=0; i < getDataAuthentication().length; i++) {
                str.append(fmt(getDataAuthentication()[i]));
            }
        str.append(fmt(getOriginAuthentication()));
        return str.toString();
    }

}

