// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class common_detailHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(common_detailHolder.class.getName());

    private BigDecimal code;
    private String message;
    private String error_stack;
    private String source_document;
    private String advice;

    public void setCode(BigDecimal code) {
        this.code = code;
    }

    public BigDecimal getCode() {
        return this.code;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getMessage() {
        return this.message;
    }

    public void setError_stack(String error_stack) {
        this.error_stack = error_stack;
    }

    public String getError_stack() {
        return this.error_stack;
    }

    public void setSource_document(String source_document) {
        this.source_document = source_document;
    }

    public String getSource_document() {
        return this.source_document;
    }

    public void setAdvice(String advice) {
        this.advice = advice;
    }

    public String getAdvice() {
        return this.advice;
    }

    public common_detailHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("common_detail(");
        str.append(" code=").append(getCode());
        str.append(" message=").append(getMessage());
        str.append(" error_stack=").append(getError_stack());
        str.append(" source_document=").append(getSource_document());
        str.append(" advice=").append(getAdvice());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getCode()));
        str.append(fmt(getMessage()));
        str.append(fmt(getError_stack()));
        str.append(fmt(getSource_document()));
        str.append(fmt(getAdvice()));
        return str.toString();
    }

}

