// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class CredentialsHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(CredentialsHolder.class.getName());

    private String credCountry;
    private String credType;
    private String serialNumber;
    private String credNumber;
    private String issuer;
    private String issuerCode;
    private String issueCity;
    private Date issueDate;
    private Date expiryDate;

    public void setCredCountry(String CredCountry) {
        this.credCountry = CredCountry;
    }

    public String getCredCountry() {
        return this.credCountry;
    }

    public void setCredType(String CredType) {
        this.credType = CredType;
    }

    public String getCredType() {
        return this.credType;
    }

    public void setSerialNumber(String SerialNumber) {
        this.serialNumber = SerialNumber;
    }

    public String getSerialNumber() {
        return this.serialNumber;
    }

    public void setCredNumber(String CredNumber) {
        this.credNumber = CredNumber;
    }

    public String getCredNumber() {
        return this.credNumber;
    }

    public void setIssuer(String Issuer) {
        this.issuer = Issuer;
    }

    public String getIssuer() {
        return this.issuer;
    }

    public void setIssuerCode(String IssuerCode) {
        this.issuerCode = IssuerCode;
    }

    public String getIssuerCode() {
        return this.issuerCode;
    }

    public void setIssueCity(String IssueCity) {
        this.issueCity = IssueCity;
    }

    public String getIssueCity() {
        return this.issueCity;
    }

    public void setIssueDate(Date IssueDate) {
        this.issueDate = IssueDate;
    }

    public Date getIssueDate() {
        return this.issueDate;
    }

    public void setExpiryDate(Date ExpiryDate) {
        this.expiryDate = ExpiryDate;
    }

    public Date getExpiryDate() {
        return this.expiryDate;
    }

    public CredentialsHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("Credentials(");
        str.append(" credCountry=").append(getCredCountry());
        str.append(" credType=").append(getCredType());
        str.append(" serialNumber=").append(getSerialNumber());
        str.append(" credNumber=").append(getCredNumber());
        str.append(" issuer=").append(getIssuer());
        str.append(" issuerCode=").append(getIssuerCode());
        str.append(" issueCity=").append(getIssueCity());
        str.append(" issueDate=").append(getIssueDate());
        str.append(" expiryDate=").append(getExpiryDate());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getCredCountry()));
        str.append(fmt(getCredType()));
        str.append(fmt(getSerialNumber()));
        str.append(fmt(getCredNumber()));
        str.append(fmt(getIssuer()));
        str.append(fmt(getIssuerCode()));
        str.append(fmt(getIssueCity()));
        str.append(fmt(getIssueDate()));
        str.append(fmt(getExpiryDate()));
        return str.toString();
    }

}

