// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class DataIntegrityHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(DataIntegrityHolder.class.getName());

    private String contentIntegrity;
    private String sequenceIntegrity;

    public void setContentIntegrity(String ContentIntegrity) {
        this.contentIntegrity = ContentIntegrity;
    }

    public String getContentIntegrity() {
        return this.contentIntegrity;
    }

    public void setSequenceIntegrity(String SequenceIntegrity) {
        this.sequenceIntegrity = SequenceIntegrity;
    }

    public String getSequenceIntegrity() {
        return this.sequenceIntegrity;
    }

    public DataIntegrityHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("DataIntegrity(");
        str.append(" contentIntegrity=").append(getContentIntegrity());
        str.append(" sequenceIntegrity=").append(getSequenceIntegrity());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getContentIntegrity()));
        str.append(fmt(getSequenceIntegrity()));
        return str.toString();
    }

}

