// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class DataAuthenticationHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(DataAuthenticationHolder.class.getName());

    private X509DataHolder x509Data;
    private String principalID;

    public void setX509Data(X509DataHolder X509Data) {
        this.x509Data = X509Data;
    }

    public X509DataHolder getX509Data() {
        return this.x509Data;
    }

    public void setPrincipalID(String PrincipalID) {
        this.principalID = PrincipalID;
    }

    public String getPrincipalID() {
        return this.principalID;
    }

    public DataAuthenticationHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("DataAuthentication(");
        str.append(" x509Data=").append(getX509Data());
        str.append(" principalID=").append(getPrincipalID());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getX509Data()));
        str.append(fmt(getPrincipalID()));
        return str.toString();
    }

}

