// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class faultHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(faultHolder.class.getName());

    private String faultcode;
    private String faultstring;
    private String faultactor;
    private detailHolder detail;

    public void setFaultcode(String faultcode) {
        this.faultcode = faultcode;
    }

    public String getFaultcode() {
        return this.faultcode;
    }

    public void setFaultstring(String faultstring) {
        this.faultstring = faultstring;
    }

    public String getFaultstring() {
        return this.faultstring;
    }

    public void setFaultactor(String faultactor) {
        this.faultactor = faultactor;
    }

    public String getFaultactor() {
        return this.faultactor;
    }

    public void setDetail(detailHolder detail) {
        this.detail = detail;
    }

    public detailHolder getDetail() {
        return this.detail;
    }

    public faultHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("fault(");
        str.append(" faultcode=").append(getFaultcode());
        str.append(" faultstring=").append(getFaultstring());
        str.append(" faultactor=").append(getFaultactor());
        str.append(" detail=").append(getDetail());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getFaultcode()));
        str.append(fmt(getFaultstring()));
        str.append(fmt(getFaultactor()));
        str.append(fmt(getDetail()));
        return str.toString();
    }

}

