// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class FilterHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(FilterHolder.class.getName());

    private Date fromDate;
    private Date toDate;
    private BigDecimal state;
    private String txID;
    private String stan;
    private String sysID;
    private String bIN;
    private String remID;
    private String cardID;
    private String cardPAN;
    private String accountID;
    private String approvalCode;
    private String docID;
    private String docDate;
    private String phone;
    private String orgCountry;
    private BigDecimal errCode;

    public void setFromDate(Date FromDate) {
        this.fromDate = FromDate;
    }

    public Date getFromDate() {
        return this.fromDate;
    }

    public void setToDate(Date ToDate) {
        this.toDate = ToDate;
    }

    public Date getToDate() {
        return this.toDate;
    }

    public void setState(BigDecimal State) {
        this.state = State;
    }

    public BigDecimal getState() {
        return this.state;
    }

    public void setTxID(String TxID) {
        this.txID = TxID;
    }

    public String getTxID() {
        return this.txID;
    }

    public void setStan(String Stan) {
        this.stan = Stan;
    }

    public String getStan() {
        return this.stan;
    }

    public void setSysID(String SysID) {
        this.sysID = SysID;
    }

    public String getSysID() {
        return this.sysID;
    }

    public void setBIN(String BIN) {
        this.bIN = BIN;
    }

    public String getBIN() {
        return this.bIN;
    }

    public void setRemID(String RemID) {
        this.remID = RemID;
    }

    public String getRemID() {
        return this.remID;
    }

    public void setCardID(String CardID) {
        this.cardID = CardID;
    }

    public String getCardID() {
        return this.cardID;
    }

    public void setCardPAN(String CardPAN) {
        this.cardPAN = CardPAN;
    }

    public String getCardPAN() {
        return this.cardPAN;
    }

    public void setAccountID(String AccountID) {
        this.accountID = AccountID;
    }

    public String getAccountID() {
        return this.accountID;
    }

    public void setApprovalCode(String ApprovalCode) {
        this.approvalCode = ApprovalCode;
    }

    public String getApprovalCode() {
        return this.approvalCode;
    }

    public void setDocID(String DocID) {
        this.docID = DocID;
    }

    public String getDocID() {
        return this.docID;
    }

    public void setDocDate(String DocDate) {
        this.docDate = DocDate;
    }

    public String getDocDate() {
        return this.docDate;
    }

    public void setPhone(String Phone) {
        this.phone = Phone;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setOrgCountry(String OrgCountry) {
        this.orgCountry = OrgCountry;
    }

    public String getOrgCountry() {
        return this.orgCountry;
    }

    public void setErrCode(BigDecimal ErrCode) {
        this.errCode = ErrCode;
    }

    public BigDecimal getErrCode() {
        return this.errCode;
    }

    public FilterHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("Filter(");
        str.append(" fromDate=").append(getFromDate());
        str.append(" toDate=").append(getToDate());
        str.append(" state=").append(getState());
        str.append(" txID=").append(getTxID());
        str.append(" stan=").append(getStan());
        str.append(" sysID=").append(getSysID());
        str.append(" bIN=").append(getBIN());
        str.append(" remID=").append(getRemID());
        str.append(" cardID=").append(getCardID());
        str.append(" cardPAN=").append(getCardPAN());
        str.append(" accountID=").append(getAccountID());
        str.append(" approvalCode=").append(getApprovalCode());
        str.append(" docID=").append(getDocID());
        str.append(" docDate=").append(getDocDate());
        str.append(" phone=").append(getPhone());
        str.append(" orgCountry=").append(getOrgCountry());
        str.append(" errCode=").append(getErrCode());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getFromDate()));
        str.append(fmt(getToDate()));
        str.append(fmt(getState()));
        str.append(fmt(getTxID()));
        str.append(fmt(getStan()));
        str.append(fmt(getSysID()));
        str.append(fmt(getBIN()));
        str.append(fmt(getRemID()));
        str.append(fmt(getCardID()));
        str.append(fmt(getCardPAN()));
        str.append(fmt(getAccountID()));
        str.append(fmt(getApprovalCode()));
        str.append(fmt(getDocID()));
        str.append(fmt(getDocDate()));
        str.append(fmt(getPhone()));
        str.append(fmt(getOrgCountry()));
        str.append(fmt(getErrCode()));
        return str.toString();
    }

}

