// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class LimitTypeHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(LimitTypeHolder.class.getName());

    private String cur;
    private BigDecimal dayAmount;
    private BigDecimal weekAmount;
    private BigDecimal monthAmount;

    public void setCur(String Cur) {
        this.cur = Cur;
    }

    public String getCur() {
        return this.cur;
    }

    public void setDayAmount(BigDecimal DayAmount) {
        this.dayAmount = DayAmount;
    }

    public BigDecimal getDayAmount() {
        return this.dayAmount;
    }

    public void setWeekAmount(BigDecimal WeekAmount) {
        this.weekAmount = WeekAmount;
    }

    public BigDecimal getWeekAmount() {
        return this.weekAmount;
    }

    public void setMonthAmount(BigDecimal MonthAmount) {
        this.monthAmount = MonthAmount;
    }

    public BigDecimal getMonthAmount() {
        return this.monthAmount;
    }

    public LimitTypeHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("LimitType(");
        str.append(" cur=").append(getCur());
        str.append(" dayAmount=").append(getDayAmount());
        str.append(" weekAmount=").append(getWeekAmount());
        str.append(" monthAmount=").append(getMonthAmount());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getCur()));
        str.append(fmt(getDayAmount()));
        str.append(fmt(getWeekAmount()));
        str.append(fmt(getMonthAmount()));
        return str.toString();
    }

}

