// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class MtBriefHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(MtBriefHolder.class.getName());

    private String remName;
    private String remID;
    private String txID;
    private FundsHolder orgFunds;
    private FundsHolder dstFunds;
    private FundsHolder payFunds;
    private DstPayRateHolder dstPayRate;
    private ExtFundsHolder[] taxFunds;
    private ExtFundsHolder[] feeFunds;
    private FullNameTypeHolder payerName;
    private FullNameTypeHolder payeeName;
    private String message;
    private BigDecimal termsOfServiceVersion;

    public void setRemName(String RemName) {
        this.remName = RemName;
    }

    public String getRemName() {
        return this.remName;
    }

    public void setRemID(String RemID) {
        this.remID = RemID;
    }

    public String getRemID() {
        return this.remID;
    }

    public void setTxID(String TxID) {
        this.txID = TxID;
    }

    public String getTxID() {
        return this.txID;
    }

    public void setOrgFunds(FundsHolder OrgFunds) {
        this.orgFunds = OrgFunds;
    }

    public FundsHolder getOrgFunds() {
        return this.orgFunds;
    }

    public void setDstFunds(FundsHolder DstFunds) {
        this.dstFunds = DstFunds;
    }

    public FundsHolder getDstFunds() {
        return this.dstFunds;
    }

    public void setPayFunds(FundsHolder PayFunds) {
        this.payFunds = PayFunds;
    }

    public FundsHolder getPayFunds() {
        return this.payFunds;
    }

    public void setDstPayRate(DstPayRateHolder DstPayRate) {
        this.dstPayRate = DstPayRate;
    }

    public DstPayRateHolder getDstPayRate() {
        return this.dstPayRate;
    }

    public void setTaxFunds(ExtFundsHolder[] TaxFunds) {
        this.taxFunds = TaxFunds;
    }

    public ExtFundsHolder[] getTaxFunds() {
        return this.taxFunds;
    }

    public void setFeeFunds(ExtFundsHolder[] FeeFunds) {
        this.feeFunds = FeeFunds;
    }

    public ExtFundsHolder[] getFeeFunds() {
        return this.feeFunds;
    }

    public void setPayerName(FullNameTypeHolder PayerName) {
        this.payerName = PayerName;
    }

    public FullNameTypeHolder getPayerName() {
        return this.payerName;
    }

    public void setPayeeName(FullNameTypeHolder PayeeName) {
        this.payeeName = PayeeName;
    }

    public FullNameTypeHolder getPayeeName() {
        return this.payeeName;
    }

    public void setMessage(String Message) {
        this.message = Message;
    }

    public String getMessage() {
        return this.message;
    }

    public void setTermsOfServiceVersion(BigDecimal TermsOfServiceVersion) {
        this.termsOfServiceVersion = TermsOfServiceVersion;
    }

    public BigDecimal getTermsOfServiceVersion() {
        return this.termsOfServiceVersion;
    }

    public MtBriefHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("MtBrief(");
        str.append(" remName=").append(getRemName());
        str.append(" remID=").append(getRemID());
        str.append(" txID=").append(getTxID());
        str.append(" orgFunds=").append(getOrgFunds());
        str.append(" dstFunds=").append(getDstFunds());
        str.append(" payFunds=").append(getPayFunds());
        str.append(" dstPayRate=").append(getDstPayRate());
        if ( getTaxFunds() != null )
            for (int i=0; i < getTaxFunds().length; i++) {
                str.append(" taxFunds["+i+"]=").append(getTaxFunds()[i]);
            }
        if ( getFeeFunds() != null )
            for (int i=0; i < getFeeFunds().length; i++) {
                str.append(" feeFunds["+i+"]=").append(getFeeFunds()[i]);
            }
        str.append(" payerName=").append(getPayerName());
        str.append(" payeeName=").append(getPayeeName());
        str.append(" message=").append(getMessage());
        str.append(" termsOfServiceVersion=").append(getTermsOfServiceVersion());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getRemName()));
        str.append(fmt(getRemID()));
        str.append(fmt(getTxID()));
        str.append(fmt(getOrgFunds()));
        str.append(fmt(getDstFunds()));
        str.append(fmt(getPayFunds()));
        str.append(fmt(getDstPayRate()));
        if ( getTaxFunds() != null )
            for (int i=0; i < getTaxFunds().length; i++) {
                str.append(fmt(getTaxFunds()[i]));
            }
        if ( getFeeFunds() != null )
            for (int i=0; i < getFeeFunds().length; i++) {
                str.append(fmt(getFeeFunds()[i]));
            }
        str.append(fmt(getPayerName()));
        str.append(fmt(getPayeeName()));
        str.append(fmt(getMessage()));
        str.append(fmt(getTermsOfServiceVersion()));
        return str.toString();
    }

}

