// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class ParamTypeHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(ParamTypeHolder.class.getName());

    private String pName;
    private String pValue;

    public void setPName(String PName) {
        this.pName = PName;
    }

    public String getPName() {
        return this.pName;
    }

    public void setPValue(String PValue) {
        this.pValue = PValue;
    }

    public String getPValue() {
        return this.pValue;
    }

    public ParamTypeHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("ParamType(");
        str.append(" pName=").append(getPName());
        str.append(" pValue=").append(getPValue());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getPName()));
        str.append(fmt(getPValue()));
        return str.toString();
    }

}

