// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class ReqAuthMoneyPayHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(ReqAuthMoneyPayHolder.class.getName());

    private String stan;
    private String timeStamp;
    private String sysID;
    private BigDecimal userID;
    private String txID;
    private PersonHolder payee;
    private FundsHolder dstFunds;
    private FundsHolder payFunds;
    private DstPayRateHolder dstPayRate;
    private ExtFundsHolder[] taxFunds;
    private ExtFundsHolder[] feeFunds;
    private String docID;
    private String docDate;
    private String approvalCode;
    private String cardTxID;
    private String signature;

    public void setStan(String Stan) {
        this.stan = Stan;
    }

    public String getStan() {
        return this.stan;
    }

    public void setTimeStamp(String TimeStamp) {
        this.timeStamp = TimeStamp;
    }

    public String getTimeStamp() {
        return this.timeStamp;
    }

    public void setSysID(String SysID) {
        this.sysID = SysID;
    }

    public String getSysID() {
        return this.sysID;
    }

    public void setUserID(BigDecimal UserID) {
        this.userID = UserID;
    }

    public BigDecimal getUserID() {
        return this.userID;
    }

    public void setTxID(String TxID) {
        this.txID = TxID;
    }

    public String getTxID() {
        return this.txID;
    }

    public void setPayee(PersonHolder Payee) {
        this.payee = Payee;
    }

    public PersonHolder getPayee() {
        return this.payee;
    }

    public void setDstFunds(FundsHolder DstFunds) {
        this.dstFunds = DstFunds;
    }

    public FundsHolder getDstFunds() {
        return this.dstFunds;
    }

    public void setPayFunds(FundsHolder PayFunds) {
        this.payFunds = PayFunds;
    }

    public FundsHolder getPayFunds() {
        return this.payFunds;
    }

    public void setDstPayRate(DstPayRateHolder DstPayRate) {
        this.dstPayRate = DstPayRate;
    }

    public DstPayRateHolder getDstPayRate() {
        return this.dstPayRate;
    }

    public void setTaxFunds(ExtFundsHolder[] TaxFunds) {
        this.taxFunds = TaxFunds;
    }

    public ExtFundsHolder[] getTaxFunds() {
        return this.taxFunds;
    }

    public void setFeeFunds(ExtFundsHolder[] FeeFunds) {
        this.feeFunds = FeeFunds;
    }

    public ExtFundsHolder[] getFeeFunds() {
        return this.feeFunds;
    }

    public void setDocID(String DocID) {
        this.docID = DocID;
    }

    public String getDocID() {
        return this.docID;
    }

    public void setDocDate(String DocDate) {
        this.docDate = DocDate;
    }

    public String getDocDate() {
        return this.docDate;
    }

    public void setApprovalCode(String ApprovalCode) {
        this.approvalCode = ApprovalCode;
    }

    public String getApprovalCode() {
        return this.approvalCode;
    }

    public void setCardTxID(String CardTxID) {
        this.cardTxID = CardTxID;
    }

    public String getCardTxID() {
        return this.cardTxID;
    }

    public void setSignature(String Signature) {
        this.signature = Signature;
    }

    public String getSignature() {
        return this.signature;
    }

    public ReqAuthMoneyPayHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("ReqAuthMoneyPay(");
        str.append(" stan=").append(getStan());
        str.append(" timeStamp=").append(getTimeStamp());
        str.append(" sysID=").append(getSysID());
        str.append(" userID=").append(getUserID());
        str.append(" txID=").append(getTxID());
        str.append(" payee=").append(getPayee());
        str.append(" dstFunds=").append(getDstFunds());
        str.append(" payFunds=").append(getPayFunds());
        str.append(" dstPayRate=").append(getDstPayRate());
        if ( getTaxFunds() != null )
            for (int i=0; i < getTaxFunds().length; i++) {
                str.append(" taxFunds["+i+"]=").append(getTaxFunds()[i]);
            }
        if ( getFeeFunds() != null )
            for (int i=0; i < getFeeFunds().length; i++) {
                str.append(" feeFunds["+i+"]=").append(getFeeFunds()[i]);
            }
        str.append(" docID=").append(getDocID());
        str.append(" docDate=").append(getDocDate());
        str.append(" approvalCode=").append(getApprovalCode());
        str.append(" cardTxID=").append(getCardTxID());
        str.append(" signature=").append(getSignature());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getStan()));
        str.append(fmt(getTimeStamp()));
        str.append(fmt(getSysID()));
        str.append(fmt(getUserID()));
        str.append(fmt(getTxID()));
        str.append(fmt(getPayee()));
        str.append(fmt(getDstFunds()));
        str.append(fmt(getPayFunds()));
        str.append(fmt(getDstPayRate()));
        if ( getTaxFunds() != null )
            for (int i=0; i < getTaxFunds().length; i++) {
                str.append(fmt(getTaxFunds()[i]));
            }
        if ( getFeeFunds() != null )
            for (int i=0; i < getFeeFunds().length; i++) {
                str.append(fmt(getFeeFunds()[i]));
            }
        str.append(fmt(getDocID()));
        str.append(fmt(getDocDate()));
        str.append(fmt(getApprovalCode()));
        str.append(fmt(getCardTxID()));
        return str.toString();
    }

}

