// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class ReqPayEndHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(ReqPayEndHolder.class.getName());

    private String stan;
    private String timeStamp;
    private String docID;
    private String docDate;
    private String cardID;
    private String cardPAN;
    private String accountNumber;
    private BigDecimal reason;
    private String description;
    private String mtID;
    private String mtDate;
    private String mTCN;
    private String approvalCode;
    private String cardTxID;
    private String signature;

    public void setStan(String Stan) {
        this.stan = Stan;
    }

    public String getStan() {
        return this.stan;
    }

    public void setTimeStamp(String TimeStamp) {
        this.timeStamp = TimeStamp;
    }

    public String getTimeStamp() {
        return this.timeStamp;
    }

    public void setDocID(String DocID) {
        this.docID = DocID;
    }

    public String getDocID() {
        return this.docID;
    }

    public void setDocDate(String DocDate) {
        this.docDate = DocDate;
    }

    public String getDocDate() {
        return this.docDate;
    }

    public void setCardID(String CardID) {
        this.cardID = CardID;
    }

    public String getCardID() {
        return this.cardID;
    }

    public void setCardPAN(String CardPAN) {
        this.cardPAN = CardPAN;
    }

    public String getCardPAN() {
        return this.cardPAN;
    }

    public void setAccountNumber(String AccountNumber) {
        this.accountNumber = AccountNumber;
    }

    public String getAccountNumber() {
        return this.accountNumber;
    }

    public void setReason(BigDecimal Reason) {
        this.reason = Reason;
    }

    public BigDecimal getReason() {
        return this.reason;
    }

    public void setDescription(String Description) {
        this.description = Description;
    }

    public String getDescription() {
        return this.description;
    }

    public void setMtID(String MtID) {
        this.mtID = MtID;
    }

    public String getMtID() {
        return this.mtID;
    }

    public void setMtDate(String MtDate) {
        this.mtDate = MtDate;
    }

    public String getMtDate() {
        return this.mtDate;
    }

    public void setMTCN(String MTCN) {
        this.mTCN = MTCN;
    }

    public String getMTCN() {
        return this.mTCN;
    }

    public void setApprovalCode(String ApprovalCode) {
        this.approvalCode = ApprovalCode;
    }

    public String getApprovalCode() {
        return this.approvalCode;
    }

    public void setCardTxID(String CardTxID) {
        this.cardTxID = CardTxID;
    }

    public String getCardTxID() {
        return this.cardTxID;
    }

    public void setSignature(String Signature) {
        this.signature = Signature;
    }

    public String getSignature() {
        return this.signature;
    }

    public ReqPayEndHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("ReqPayEnd(");
        str.append(" stan=").append(getStan());
        str.append(" timeStamp=").append(getTimeStamp());
        str.append(" docID=").append(getDocID());
        str.append(" docDate=").append(getDocDate());
        str.append(" cardID=").append(getCardID());
        str.append(" cardPAN=").append(getCardPAN());
        str.append(" accountNumber=").append(getAccountNumber());
        str.append(" reason=").append(getReason());
        str.append(" description=").append(getDescription());
        str.append(" mtID=").append(getMtID());
        str.append(" mtDate=").append(getMtDate());
        str.append(" mTCN=").append(getMTCN());
        str.append(" approvalCode=").append(getApprovalCode());
        str.append(" cardTxID=").append(getCardTxID());
        str.append(" signature=").append(getSignature());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getStan()));
        str.append(fmt(getTimeStamp()));
        str.append(fmt(getDocID()));
        str.append(fmt(getDocDate()));
        str.append(fmt(getCardID()));
        str.append(fmt(getCardPAN()));
        str.append(fmt(getAccountNumber()));
        str.append(fmt(getReason()));
        str.append(fmt(getDescription()));
        str.append(fmt(getMtID()));
        str.append(fmt(getMtDate()));
        str.append(fmt(getMTCN()));
        str.append(fmt(getApprovalCode()));
        str.append(fmt(getCardTxID()));
        return str.toString();
    }

}

