// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class SubjItemHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(SubjItemHolder.class.getName());

    private String sysID;
    private BigDecimal sysType;
    private String isActive;
    private String sysName;
    private String phone;

    public void setSysID(String SysID) {
        this.sysID = SysID;
    }

    public String getSysID() {
        return this.sysID;
    }

    public void setSysType(BigDecimal SysType) {
        this.sysType = SysType;
    }

    public BigDecimal getSysType() {
        return this.sysType;
    }

    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    public String getIsActive() {
        return this.isActive;
    }

    public void setSysName(String SysName) {
        this.sysName = SysName;
    }

    public String getSysName() {
        return this.sysName;
    }

    public void setPhone(String Phone) {
        this.phone = Phone;
    }

    public String getPhone() {
        return this.phone;
    }

    public SubjItemHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("SubjItem(");
        str.append(" sysID=").append(getSysID());
        str.append(" sysType=").append(getSysType());
        str.append(" isActive=").append(getIsActive());
        str.append(" sysName=").append(getSysName());
        str.append(" phone=").append(getPhone());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getSysID()));
        str.append(fmt(getSysType()));
        str.append(fmt(getIsActive()));
        str.append(fmt(getSysName()));
        str.append(fmt(getPhone()));
        return str.toString();
    }

}

