// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class SubjLimitTypeHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(SubjLimitTypeHolder.class.getName());

    private String sysID;
    private LimitTypeHolder limit;

    public void setSysID(String SysID) {
        this.sysID = SysID;
    }

    public String getSysID() {
        return this.sysID;
    }

    public void setLimit(LimitTypeHolder Limit) {
        this.limit = Limit;
    }

    public LimitTypeHolder getLimit() {
        return this.limit;
    }

    public SubjLimitTypeHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("SubjLimitType(");
        str.append(" sysID=").append(getSysID());
        str.append(" limit=").append(getLimit());
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getSysID()));
        str.append(fmt(getLimit()));
        return str.toString();
    }

}

