// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class TxHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(TxHolder.class.getName());

    private String txID;
    private String insDate;
    private String updDate;
    private String sysID;
    private String bIN;
    private String cardID;
    private String cardPAN;
    private String accountID;
    private StateHistoryHolder stateHistory;
    private String mTCN;
    private String remID;
    private String mtID;
    private String phone;
    private String docID;
    private String docDate;
    private String approvalCode;
    private String cardTxID;
    private String orgCountry;
    private BigDecimal errCode;
    private FundsHolder orgFunds;
    private FundsHolder dstFunds;
    private FundsHolder payFunds;
    private DstPayRateHolder dstPayRate;
    private ExtFundsHolder[] taxFunds;
    private ExtFundsHolder[] feeFunds;

    public void setTxID(String TxID) {
        this.txID = TxID;
    }

    public String getTxID() {
        return this.txID;
    }

    public void setInsDate(String InsDate) {
        this.insDate = InsDate;
    }

    public String getInsDate() {
        return this.insDate;
    }

    public void setUpdDate(String UpdDate) {
        this.updDate = UpdDate;
    }

    public String getUpdDate() {
        return this.updDate;
    }

    public void setSysID(String SysID) {
        this.sysID = SysID;
    }

    public String getSysID() {
        return this.sysID;
    }

    public void setBIN(String BIN) {
        this.bIN = BIN;
    }

    public String getBIN() {
        return this.bIN;
    }

    public void setCardID(String CardID) {
        this.cardID = CardID;
    }

    public String getCardID() {
        return this.cardID;
    }

    public void setCardPAN(String CardPAN) {
        this.cardPAN = CardPAN;
    }

    public String getCardPAN() {
        return this.cardPAN;
    }

    public void setAccountID(String AccountID) {
        this.accountID = AccountID;
    }

    public String getAccountID() {
        return this.accountID;
    }

    public void setStateHistory(StateHistoryHolder StateHistory) {
        this.stateHistory = StateHistory;
    }

    public StateHistoryHolder getStateHistory() {
        return this.stateHistory;
    }

    public void setMTCN(String MTCN) {
        this.mTCN = MTCN;
    }

    public String getMTCN() {
        return this.mTCN;
    }

    public void setRemID(String RemID) {
        this.remID = RemID;
    }

    public String getRemID() {
        return this.remID;
    }

    public void setMtID(String MtID) {
        this.mtID = MtID;
    }

    public String getMtID() {
        return this.mtID;
    }

    public void setPhone(String Phone) {
        this.phone = Phone;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setDocID(String DocID) {
        this.docID = DocID;
    }

    public String getDocID() {
        return this.docID;
    }

    public void setDocDate(String DocDate) {
        this.docDate = DocDate;
    }

    public String getDocDate() {
        return this.docDate;
    }

    public void setApprovalCode(String ApprovalCode) {
        this.approvalCode = ApprovalCode;
    }

    public String getApprovalCode() {
        return this.approvalCode;
    }

    public void setCardTxID(String CardTxID) {
        this.cardTxID = CardTxID;
    }

    public String getCardTxID() {
        return this.cardTxID;
    }

    public void setOrgCountry(String OrgCountry) {
        this.orgCountry = OrgCountry;
    }

    public String getOrgCountry() {
        return this.orgCountry;
    }

    public void setErrCode(BigDecimal ErrCode) {
        this.errCode = ErrCode;
    }

    public BigDecimal getErrCode() {
        return this.errCode;
    }

    public void setOrgFunds(FundsHolder OrgFunds) {
        this.orgFunds = OrgFunds;
    }

    public FundsHolder getOrgFunds() {
        return this.orgFunds;
    }

    public void setDstFunds(FundsHolder DstFunds) {
        this.dstFunds = DstFunds;
    }

    public FundsHolder getDstFunds() {
        return this.dstFunds;
    }

    public void setPayFunds(FundsHolder PayFunds) {
        this.payFunds = PayFunds;
    }

    public FundsHolder getPayFunds() {
        return this.payFunds;
    }

    public void setDstPayRate(DstPayRateHolder DstPayRate) {
        this.dstPayRate = DstPayRate;
    }

    public DstPayRateHolder getDstPayRate() {
        return this.dstPayRate;
    }

    public void setTaxFunds(ExtFundsHolder[] TaxFunds) {
        this.taxFunds = TaxFunds;
    }

    public ExtFundsHolder[] getTaxFunds() {
        return this.taxFunds;
    }

    public void setFeeFunds(ExtFundsHolder[] FeeFunds) {
        this.feeFunds = FeeFunds;
    }

    public ExtFundsHolder[] getFeeFunds() {
        return this.feeFunds;
    }

    public TxHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("Tx(");
        str.append(" txID=").append(getTxID());
        str.append(" insDate=").append(getInsDate());
        str.append(" updDate=").append(getUpdDate());
        str.append(" sysID=").append(getSysID());
        str.append(" bIN=").append(getBIN());
        str.append(" cardID=").append(getCardID());
        str.append(" cardPAN=").append(getCardPAN());
        str.append(" accountID=").append(getAccountID());
        str.append(" stateHistory=").append(getStateHistory());
        str.append(" mTCN=").append(getMTCN());
        str.append(" remID=").append(getRemID());
        str.append(" mtID=").append(getMtID());
        str.append(" phone=").append(getPhone());
        str.append(" docID=").append(getDocID());
        str.append(" docDate=").append(getDocDate());
        str.append(" approvalCode=").append(getApprovalCode());
        str.append(" cardTxID=").append(getCardTxID());
        str.append(" orgCountry=").append(getOrgCountry());
        str.append(" errCode=").append(getErrCode());
        str.append(" orgFunds=").append(getOrgFunds());
        str.append(" dstFunds=").append(getDstFunds());
        str.append(" payFunds=").append(getPayFunds());
        str.append(" dstPayRate=").append(getDstPayRate());
        if ( getTaxFunds() != null )
            for (int i=0; i < getTaxFunds().length; i++) {
                str.append(" taxFunds["+i+"]=").append(getTaxFunds()[i]);
            }
        if ( getFeeFunds() != null )
            for (int i=0; i < getFeeFunds().length; i++) {
                str.append(" feeFunds["+i+"]=").append(getFeeFunds()[i]);
            }
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getTxID()));
        str.append(fmt(getInsDate()));
        str.append(fmt(getUpdDate()));
        str.append(fmt(getSysID()));
        str.append(fmt(getBIN()));
        str.append(fmt(getCardID()));
        str.append(fmt(getCardPAN()));
        str.append(fmt(getAccountID()));
        str.append(fmt(getStateHistory()));
        str.append(fmt(getMTCN()));
        str.append(fmt(getRemID()));
        str.append(fmt(getMtID()));
        str.append(fmt(getPhone()));
        str.append(fmt(getDocID()));
        str.append(fmt(getDocDate()));
        str.append(fmt(getApprovalCode()));
        str.append(fmt(getCardTxID()));
        str.append(fmt(getOrgCountry()));
        str.append(fmt(getErrCode()));
        str.append(fmt(getOrgFunds()));
        str.append(fmt(getDstFunds()));
        str.append(fmt(getPayFunds()));
        str.append(fmt(getDstPayRate()));
        if ( getTaxFunds() != null )
            for (int i=0; i < getTaxFunds().length; i++) {
                str.append(fmt(getTaxFunds()[i]));
            }
        if ( getFeeFunds() != null )
            for (int i=0; i < getFeeFunds().length; i++) {
                str.append(fmt(getFeeFunds()[i]));
            }
        return str.toString();
    }

}

