// This file was automatically generated by udr2java.sh utility.
// ($Id: udr2java.sh,v 1.60 2015/07/17 05:29:18 black Exp $)
// Do not edit, please!

/**
 * Copyright (C) GRS24, Inc. 2014-2015.
 * All rights reserved.
 */

package com.grs24.msg;

import org.apache.log4j.Logger;
import com.grs24.core.Stickable;
import java.util.Date;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.springframework.roo.addon.json.annotations.RooJson;

@RooJson(deepSerialize = true, iso8601Dates = true)
public class UpdDataHolder implements Stickable {
    protected static Logger syslog = Logger.getLogger(UpdDataHolder.class.getName());

    private String sysID;
    private String isActive;
    private LNameHolder lName;
    private String address;
    private String phone;
    private LimitTypeHolder tLimit;
    private SubjLimitTypeHolder[] sLimit;
    private LimitTypeHolder pLimit;
    private String x509Certificate;
    private String password;
    private ParamTypeHolder[] params;

    public void setSysID(String SysID) {
        this.sysID = SysID;
    }

    public String getSysID() {
        return this.sysID;
    }

    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    public String getIsActive() {
        return this.isActive;
    }

    public void setLName(LNameHolder LName) {
        this.lName = LName;
    }

    public LNameHolder getLName() {
        return this.lName;
    }

    public void setAddress(String Address) {
        this.address = Address;
    }

    public String getAddress() {
        return this.address;
    }

    public void setPhone(String Phone) {
        this.phone = Phone;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setTLimit(LimitTypeHolder TLimit) {
        this.tLimit = TLimit;
    }

    public LimitTypeHolder getTLimit() {
        return this.tLimit;
    }

    public void setSLimit(SubjLimitTypeHolder[] SLimit) {
        this.sLimit = SLimit;
    }

    public SubjLimitTypeHolder[] getSLimit() {
        return this.sLimit;
    }

    public void setPLimit(LimitTypeHolder PLimit) {
        this.pLimit = PLimit;
    }

    public LimitTypeHolder getPLimit() {
        return this.pLimit;
    }

    public void setX509Certificate(String X509Certificate) {
        this.x509Certificate = X509Certificate;
    }

    public String getX509Certificate() {
        return this.x509Certificate;
    }

    public void setPassword(String Password) {
        this.password = Password;
    }

    public String getPassword() {
        return this.password;
    }

    public void setParams(ParamTypeHolder[] Params) {
        this.params = Params;
    }

    public ParamTypeHolder[] getParams() {
        return this.params;
    }

    public UpdDataHolder() {
    }

    public String toString() {
        StringBuffer str = new StringBuffer();
        str.append("UpdData(");
        str.append(" sysID=").append(getSysID());
        str.append(" isActive=").append(getIsActive());
        str.append(" lName=").append(getLName());
        str.append(" address=").append(getAddress());
        str.append(" phone=").append(getPhone());
        str.append(" tLimit=").append(getTLimit());
        if ( getSLimit() != null )
            for (int i=0; i < getSLimit().length; i++) {
                str.append(" sLimit["+i+"]=").append(getSLimit()[i]);
            }
        str.append(" pLimit=").append(getPLimit());
        str.append(" x509Certificate=").append(getX509Certificate());
        str.append(" password=").append(getPassword());
        if ( getParams() != null )
            for (int i=0; i < getParams().length; i++) {
                str.append(" params["+i+"]=").append(getParams()[i]);
            }
        str.append(")");
        return str.toString();
    }

    private String fmt(Object data) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        StringBuffer str = new StringBuffer();
	if (data == null) return null;
	if (data instanceof Date) 
		str.append(sdf.format((Date)data));
     else
		str.append( (data instanceof Stickable) ? ((Stickable)data).stickString() : data);
	return str.toString();
    }

    public String stickString() {
        StringBuffer str = new StringBuffer();
        str.append(fmt(getSysID()));
        str.append(fmt(getIsActive()));
        str.append(fmt(getLName()));
        str.append(fmt(getAddress()));
        str.append(fmt(getPhone()));
        str.append(fmt(getTLimit()));
        if ( getSLimit() != null )
            for (int i=0; i < getSLimit().length; i++) {
                str.append(fmt(getSLimit()[i]));
            }
        str.append(fmt(getPLimit()));
        str.append(fmt(getX509Certificate()));
        str.append(fmt(getPassword()));
        if ( getParams() != null )
            for (int i=0; i < getParams().length; i++) {
                str.append(fmt(getParams()[i]));
            }
        return str.toString();
    }

}

