
package com.grs24.mt.unistream.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.wcfservicelib.CreatePersonRequestMessage;
import org.datacontract.schemas._2004._07.wcfservicelib.CreatePersonResponseMessage;
import org.datacontract.schemas._2004._07.wcfservicelib.FindPersonRequestMessage;
import org.datacontract.schemas._2004._07.wcfservicelib.FindPersonResponseMessage;
import org.datacontract.schemas._2004._07.wcfservicelib.FindTransferRequestMessage;
import org.datacontract.schemas._2004._07.wcfservicelib.FindTransferResponseMessage;
import org.datacontract.schemas._2004._07.wcfservicelib.GetTransferByIDRequestMessage;
import org.datacontract.schemas._2004._07.wcfservicelib.GetTransferByIDResponseMessage;
import org.datacontract.schemas._2004._07.wcfservicelib.PayoutTransferRequestMessage;
import org.datacontract.schemas._2004._07.wcfservicelib.PayoutTransferResponseMessage;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWebService", targetNamespace = "http://test.unistream.com/wcflib/")
@XmlSeeAlso({
    org.datacontract.schemas._2004._07.wcfservicelib.ObjectFactory.class,
    com.unistream.test.wcflib.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.wcfservicelib_dictionaries.ObjectFactory.class
})
public interface IWebService {

    /**
     * 
     * @param requestMessage
     * @return
     *     returns org.datacontract.schemas._2004._07.wcfservicelib.FindPersonResponseMessage
     */
    @WebMethod(operationName = "FindPerson", action = "http://test.unistream.com/wcflib/IClientsStore/FindPerson")
    @WebResult(name = "FindPersonResult", targetNamespace = "http://test.unistream.com/wcflib/")
    @RequestWrapper(localName = "FindPerson", targetNamespace = "http://test.unistream.com/wcflib/", className = "com.unistream.test.wcflib.FindPerson")
    @ResponseWrapper(localName = "FindPersonResponse", targetNamespace = "http://test.unistream.com/wcflib/", className = "com.unistream.test.wcflib.FindPersonResponse")
    public FindPersonResponseMessage findPerson(
        @WebParam(name = "requestMessage", targetNamespace = "http://test.unistream.com/wcflib/")
        FindPersonRequestMessage requestMessage);

    /**
     * 
     * @param requestMessage
     * @return
     *     returns org.datacontract.schemas._2004._07.wcfservicelib.CreatePersonResponseMessage
     */
    @WebMethod(operationName = "CreatePerson", action = "http://test.unistream.com/wcflib/IClientsStore/CreatePerson")
    @WebResult(name = "CreatePersonResult", targetNamespace = "http://test.unistream.com/wcflib/")
    @RequestWrapper(localName = "CreatePerson", targetNamespace = "http://test.unistream.com/wcflib/", className = "com.unistream.test.wcflib.CreatePerson")
    @ResponseWrapper(localName = "CreatePersonResponse", targetNamespace = "http://test.unistream.com/wcflib/", className = "com.unistream.test.wcflib.CreatePersonResponse")
    public CreatePersonResponseMessage createPerson(
        @WebParam(name = "requestMessage", targetNamespace = "http://test.unistream.com/wcflib/")
        CreatePersonRequestMessage requestMessage);

    /**
     * 
     * @param requestMessage
     * @return
     *     returns org.datacontract.schemas._2004._07.wcfservicelib.FindTransferResponseMessage
     */
    @WebMethod(operationName = "FindTransfer", action = "http://test.unistream.com/wcflib/ITransferProvider/FindTransfer")
    @WebResult(name = "FindTransferResult", targetNamespace = "http://test.unistream.com/wcflib/")
    @RequestWrapper(localName = "FindTransfer", targetNamespace = "http://test.unistream.com/wcflib/", className = "com.unistream.test.wcflib.FindTransfer")
    @ResponseWrapper(localName = "FindTransferResponse", targetNamespace = "http://test.unistream.com/wcflib/", className = "com.unistream.test.wcflib.FindTransferResponse")
    public FindTransferResponseMessage findTransfer(
        @WebParam(name = "requestMessage", targetNamespace = "http://test.unistream.com/wcflib/")
        FindTransferRequestMessage requestMessage);

    /**
     * 
     * @param requestMessage
     * @return
     *     returns org.datacontract.schemas._2004._07.wcfservicelib.PayoutTransferResponseMessage
     */
    @WebMethod(operationName = "PayoutTransfer", action = "http://test.unistream.com/wcflib/ITransferProvider/PayoutTransfer")
    @WebResult(name = "PayoutTransferResult", targetNamespace = "http://test.unistream.com/wcflib/")
    @RequestWrapper(localName = "PayoutTransfer", targetNamespace = "http://test.unistream.com/wcflib/", className = "com.unistream.test.wcflib.PayoutTransfer")
    @ResponseWrapper(localName = "PayoutTransferResponse", targetNamespace = "http://test.unistream.com/wcflib/", className = "com.unistream.test.wcflib.PayoutTransferResponse")
    public PayoutTransferResponseMessage payoutTransfer(
        @WebParam(name = "requestMessage", targetNamespace = "http://test.unistream.com/wcflib/")
        PayoutTransferRequestMessage requestMessage);

    /**
     * 
     * @param requestMessage
     * @return
     *     returns org.datacontract.schemas._2004._07.wcfservicelib.GetTransferByIDResponseMessage
     */
    @WebMethod(operationName = "GetTransferByID", action = "http://test.unistream.com/wcflib/ITransferProvider/GetTransferByID")
    @WebResult(name = "GetTransferByIDResult", targetNamespace = "http://test.unistream.com/wcflib/")
    @RequestWrapper(localName = "GetTransferByID", targetNamespace = "http://test.unistream.com/wcflib/", className = "com.unistream.test.wcflib.GetTransferByID")
    @ResponseWrapper(localName = "GetTransferByIDResponse", targetNamespace = "http://test.unistream.com/wcflib/", className = "com.unistream.test.wcflib.GetTransferByIDResponse")
    public GetTransferByIDResponseMessage getTransferByID(
        @WebParam(name = "requestMessage", targetNamespace = "http://test.unistream.com/wcflib/")
        GetTransferByIDRequestMessage requestMessage);

}
